### ISSUE TITLE
Upgrade to a web browser that supports WebVR api

### ISSUE THREAD

**Issue by playground** [moar-tech/spacerocks#1]
I'm running Chrome Canary 68.0.3435.0, when testing locally I'm getting

![image](https://user-images.githubusercontent.com/243495/40272716-02049a26-5b80-11e8-807f-cc1935af3c12.png)

Also do you have a webXR + Aframe project that I can learn from?

**Comment by stewdio** [comment]
At this time Space Rocks supports a special build of Chromium, not Chrome proper. If you follow the link in that error message it will direct you to the Chromium-WebVR download: [https://webvr.rocks/chromium](https://webvr.rocks/chromium). Perhaps when the new WebXR API lands in Chrome-stable I’ll consider rewiring Space Rocks. 

As for A-Frame, Space Rocks does not use it. See this technical write-up for more background: [Space Rocks—WebXR tech deep dive](https://medium.com/@stew_rtsmith/space-rocks-technical-deep-dive-9bf67fb8a467). Mozilla’s [A-Frame website](https://aframe.io/) is a great place to get started learning A-Frame.
